### ISSUE TITLE
NuGet packages need update

### ISSUE THREAD

**Issue by tim-lange** [stewartm83/angular-fileupload-sample#1]
Thanx for this sample project! I found one issue. If i download and run this project it does not work. Updating the "Newtonsoft.Jason" and "System.Net.Http.Formatting.Extension" fixes the problem.

**Comment by stewartm83** [comment]
Okay, thanks for the heads up. I will try update all Nuget packages in the project to see if there are any more issues.

**Comment by stewartm83** [comment]
Everything is now up to date.

Thanks
