### ISSUE TITLE
Error reading MIME multipart body part.

### ISSUE THREAD

**Issue by jdoan3** [stewartm83/angular-fileupload-sample#2]
So I am running into this error. 

System.IO.IOException: Error reading MIME multipart body part. ---> System.Web.HttpException: The client disconnected.

I believe this is due to the sizing of your images that you are uploading. When I upload a larger image in your Demo, it seems to only have uploaded 1/8 of the image. I tried incorporating the 
     httpRuntime targetFramework="4.5" maxRequestLength="30000000" and 
security
    requestFiltering
      requestLimits maxAllowedContentLength="30000000" 
    requestFiltering
       security
into your WebConfig file but had no luck. The interesting thing is that you are getting a client disconnected, which is something that I wouldn't have expected. I still haven't figured out a solution for this, so if you have one please let me know.

**Comment by stewartm83** [comment]
Okay I will have a look. Will let you what I find out.

Thanks

**Comment by stewartm83** [comment]
Hi 

This problem seems to be severe in Chrome. It works in Microsoft Edge, Firefox 43.1 and IE11 although the upload takes long to complete as expected. I will look into adding an upload progress bar to the sample but you are welcome to contribute as well. 

If you are looking for a quick solution then try [blueimp](https://github.com/blueimp/jQuery-File-Upload).

I hope it helps.

Thanks

**Comment by jdoan3** [comment]
That's interesting. I was following Jay Chase's live demo and I couldn't pick up the differences between yours in his since I noticed his worked on the file upload when it was on chrome as well. The only thing I could see is the webconfig file which incorporates the max allowed length.

**Comment by stewartm83** [comment]
Hi jdoan3

Did you manage to find a fix for this issue? If not ping me with any status. 

Thanks

**Comment by jdoan3** [comment]
Yes thanks a bunch.
