### ISSUE TITLE
Sending/Retrieving single images to the server

### ISSUE THREAD

**Issue by jdoan3** [stewartm83/angular-fileupload-sample#3]
This is more of a question rather than an issue. For individual users setting there profile picture, I would want to return a single image that he has set rather than the list of images in the upload folder. 

If I wanted to pull out a single image corresponding to the image I had uploaded only, how would I go about doing this?

In the Add method I don't see anything pertaining to the photo name that you have just uploaded how is this being sent to the server?

Thanks for clarification.

**Comment by stewartm83** [comment]
Hi 

There are many ways you can go about implementing that kind of functionality. I will give examples of how I would do it.  

You can create a folder on the file system named with the Id or name of the user, you can then save all their images into that folder with new names if you like e.g logo.png, coverpic.jpg etc. You can then retrieve the images depending on the specific user. As for uploading single images, you have to restrict them on file input control on the UI so that they can only choose one, by not setting multiple="true" on the input.

Another way, the best way, is to save all image file names in a database table or some kind of storage e.g a static json file. You can then map the image files table to the users table depending on the functionality you are trying to implement in your application. This is how most content management systems like Wordpress do it. It is all mapped in a database. But you have to write the code though.

I hope this helps

Thanks

**Comment by jdoan3** [comment]
Yes, I am aware of this where the second is the method I was going for. I guess to clarify, I was confused on how the image file/name/content was being sent to the Add() method in the fileController specifically since there are no object inputs? I'm not really familiar with how the ng-file-upload is sending the data to the controllers so that I could connect them to the specific user.

**Comment by senseicz** [comment]
@jdoan3 If you have this still unresolved, here is how you send additional data alongside the file:
1) In home.js (or anywhere where you handle sending files from a client), simply add additional property in data object you are sending:

```
Upload.upload({
              url: apiUrl,
              data: {
                  file: files,
                  username: "User 1"
              }
            })
```

2) In your API, read this data from provider.FormData[] collection:
`var username = provider.FormData["username"];`

 Hope this will help.

**Comment by DevQueen** [comment]
I'm trying to pass additional data as above, however, using your example, I can't figure out how to get the ByteArray.  Our web application allows a user to upload a file and the byte array is stored in our database.  We do not store the file in our file system.  Currently, I get the image as follows:

In my Angular Controller:

`$scope.uploadPic = function (file) {
        file.upload = Upload.upload({
            url: '/SSQV4/SSQV5/api/Document/UploadEMRDocument',
            method: 'POST',
            data: { file: file, 'emrdetail': $scope.emrDetailID}
        });
        file.upload.then(function (response) {
            $timeout(function () {
                file.result = response.data;
                $scope.imageID = file.result;
            });
        });
    };`

In my MVC Controller:

```
         `var provider = new MultipartMemoryStreamProvider();
            await Request.Content.ReadAsMultipartAsync(provider);
            var f = provider.Contents.First(); // assumes that the file is the only data

            if (f != null)
            {
                string ClientIP = IPNetworking.GetIP4Address();
                var filename = f.Headers.ContentDisposition.FileName.Trim('\"');
                filename = Path.GetFileName(filename);
                var extension = Path.GetExtension(filename).TrimStart('.');
                var buffer = await f.ReadAsByteArrayAsync();
                FileImageParameterModel pm = new FileImageParameterModel();
                pm.binFileImage = buffer;

                //pm.CompanyID = UserInfo.intMajorID;
                pm.CompanyID = 10707;
                pm.dteDocumentDate = Convert.ToDateTime("4/4/2016");
                pm.dteExpiration = Convert.ToDateTime("4/4/2017");
                pm.vchUserIP = ClientIP;
                pm.vchUploadedbyUserName = UserInfo.Username;
                pm.vchFileExtension = extension;
                CommonClient = new CommonWebApiClient();
                CommonClient.AuthorizationToken = UserInfo.AccessToken;
                int imageID = await CommonClient.InsertNewFileImage(pm);

                return Json(imageID);
            }
            else
            {
                return BadRequest("Attachment failed to upload");
            }`
```

I'm trying to use your sample code below but I can't figure out how to get the byteArray to store in my database:

`        var provider = new CustomMultipartFormDataStreamProvider(workingFolder);

```
    await Request.Content.ReadAsMultipartAsync(provider);

    var photos =
      provider.FileData
        .Select(file => new FileInfo(file.LocalFileName))
        .Select(fileInfo => new PhotoViewModel
        {
          Name = fileInfo.Name,
          Created = fileInfo.CreationTime,
          Modified = fileInfo.LastWriteTime,
          Size = fileInfo.Length/1024
        }).ToList();`
```

Please Help.

**Comment by stewartm83** [comment]
@DevQueen, I will have a look now and will post a solution asap.

Thanks

**Comment by DevQueen** [comment]
oh, that would be awesome!  Thanks!

**Comment by stewartm83** [comment]
@DevQueen 

Instead of this 

```
var provider = new CustomMultipartFormDataStreamProvider(workingFolder);
await Request.Content.ReadAsMultipartAsync(provider);

var photos =
      provider.FileData
        .Select(file => new FileInfo(file.LocalFileName))
        .Select(fileInfo => new PhotoViewModel
        {
            Name = fileInfo.Name,
            Created = fileInfo.CreationTime,
            Modified = fileInfo.LastWriteTime,
            Size = fileInfo.Length / 1024
        }).ToList();
```

try this 

```
var provider = new CustomMultipartFormDataStreamProvider(workingFolder);
await Request.Content.ReadAsMultipartAsync(provider);

var photos = new List<PhotoViewModel>();

foreach (var file in provider.FileData)
{
    var fileInfo = new FileInfo(file.LocalFileName);

    //Read Image byte array
    var imageByteArray = File.ReadAllBytes(file.LocalFileName);

    //Save image and/or data to database
    photos.Add(new PhotoViewModel
    {
        Name = fileInfo.Name,
        Created = fileInfo.CreationTime,
        Modified = fileInfo.LastWriteTime,
        Size = fileInfo.Length/1024
    });

    //Delete File from file system
    File.Delete(file.LocalFileName);
}
```

Then your _workingFolder will act like a temp location for the uploads.

Let me know if this if of any help.

Thanks

**Comment by DevQueen** [comment]
I'm going to try it.  I'll let you know if it works.  Thank you so much!

**Comment by stewartm83** [comment]
Okay cool. Happy coding.
