### ISSUE TITLE
Need to Get Byte Array and FormData not save file on hard drive

### ISSUE THREAD

**Issue by DevQueen** [stewartm83/angular-fileupload-sample#4]
I need to save the byte array along with other data to my database.  I don't need to save the file to disk.  I can't figure out how to do this. MultipartFormDataStreamProvider allows me to get the other data, but I can't get the byte array.  MultipartMemoryStreamProvider allows me to get the byte array, but not the other formdata.  Please help.

**Comment by stewartm83** [comment]
Hi  there

Sorry for the late reply. I will have a look now. 

Thanks

**Comment by stewartm83** [comment]
Hi there 

Should I close this issue. I haven't had any response for the past two months.

Thanks
