### ISSUE TITLE
web.config change for Newtonsoft.Json assembly

### ISSUE THREAD

**Issue by ghost** [stewartm83/angular-fileupload-sample#7]
After I cloned and ran the project I got the "Server Error" page with this message: 

"Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I changed the web.config entry for the NewtonsoftJson newVersion property from "7.0.0.0" to "9.0.0.0" and the project runs.

```
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed"/>
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0"/>
      </dependentAssembly>
```

to 

```
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed"/>
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="9.0.0.0"/>
      </dependentAssembly>
```

**Comment by stewartm83** [comment]
Hi Andy

There must have been some files in the packages folder from the old package. A better way of getting of this problem is to run
`update-package`

in the Package Manager Console. That should clean out any files from previous packages.

Thanks for letting me know and if you are still having any issues please feel free to post the stack trace here.

Stewart

**Comment by Henryisthebest** [comment]
Hi I am getting the same problem.. even after running update-package , i am using VS 2015 community

Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Source Error: 


Line 7:      protected void Application_Start()
Line 8:      {
Line 9:        GlobalConfiguration.Configure(WebApiConfig.Register);
Line 10:     }
Line 11:   }

Source File: C:\src\dcms\Diocese\Server\FileUploadAPI\angular-fileupload-sample-master\src\AspNetWebApi\Global.asax.cs    Line: 9

**Comment by apuchkov** [comment]
@Henryisthebest, I had the same problem. This is what helped me:

1.  Change Newtonsoft.Json nuget package version to 7.0.1

2. Update Web.config section to:
```
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed"/>
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0"/>
      </dependentAssembly>
```
3. Restore nuget packages

**Comment by stewartm83** [comment]
Thanks to @apuchkov, I have updated the web.config file and everything should build from an initial clone of the project.

Stewart
