### ISSUE TITLE
Azure blob with angular fileupload

### ISSUE THREAD

**Issue by jdoan3** [stewartm83/angular-fileupload-sample#9]
So I had a question in regards to using this with Azure's Blob storage. I ran into your Add method and started calling out my blob containers, but I realized you end up running into the issue of 
`await Request.Content.ReadAsMultipartAsync(provider))` which causes the server side code to fail.

I had to update the provider stream to AzureStorageMultipartFormDataStreamProvider as the original CustomMultipartFormDataStreamProvider did not work for the azure blob.

`public class AzureStorageMultipartFormDataStreamProvider : MultipartFormDataStreamProvider
    {
        private readonly CloudBlobContainer _blobContainer;
        private readonly string[] _supportedMimeTypes = { "images/png", "images/jpeg", "images/jpg" };

        public AzureStorageMultipartFormDataStreamProvider(CloudBlobContainer blobContainer) : base("azure")
        {
            _blobContainer = blobContainer;
        }

        public override Stream GetStream(HttpContent parent, HttpContentHeaders headers)
        {
            if (parent == null) throw new ArgumentNullException(nameof(parent));
            if (headers == null) throw new ArgumentNullException(nameof(headers));

            if (!_supportedMimeTypes.Contains(headers.ContentType.ToString().ToLower()))
            {
                throw new NotSupportedException("Only jpeg and png are supported");
            }

            // Generate a new filename for every new blob
            var fileName = Guid.NewGuid().ToString();

            CloudBlockBlob blob = _blobContainer.GetBlockBlobReference(fileName);

            if (headers.ContentType != null)
            {
                // Set appropriate content type for your uploaded file
                blob.Properties.ContentType = headers.ContentType.MediaType;
            }

            this.FileData.Add(new MultipartFileData(headers, blob.Name));

            return blob.OpenWrite();
        }
    }`

To take this into account. I noticed you were also using azure in your demo. How did you get past this to upload onto the blob?

**Comment by stewartm83** [comment]
@jdoan3 I used Azure for the web application only and stored the images on the file system. I did not explore that option. However this looks like an interesting feature to add. 

Can you may be create an extra controller that make use of blob containers with the AzureStorageMultipartFormDataStreamProvider that you have created already. 
Make a pull request and then I can include it into this code repo.

It might be useful to someone out there.

Thanks
